on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: exponentialcherub/deploy-pi/.github/workflows/deploy-pi.yml@v1.0.5
    with:
      app-name: "fpl-notifier"
      startup-cmd: "python poller.py"
      branch: "main"
    secrets: inherit
